### ISSUE TITLE
Authentication Errors

### ISSUE THREAD

**Issue by pjockey** [m0ranwad/nba-led-scoreboard#1]
**Describe the bug**
Authenitcation error receive when trying to clone the repo.

**To Reproduce**

1. remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/bkircher/nba-led-scoreboard/'

**Comment by m0ranwad** [comment]
Oof, my mistake. I updated my github username but forgot to update the URL in the README. 

Let me know if following the updated documentation works. 

`git clone --recursive https://github.com/m0ranwad/nba-led-scoreboard
`
